imports:
    - { resource: config_dev.yml }

web_profiler:
    toolbar: false
    intercept_redirects: false

parameters:
    max_products_category_removal: 20
    installer_data:       PimInstallerBundle:minimal
    upload_dir:           '%kernel.root_dir%/../var/cache/uploads/product'
    archive_dir:          '%kernel.root_dir%/../var/cache/archive'
    catalog_storage_dir:  '%kernel.root_dir%/../var/cache/file_storage/catalog'
    tmp_storage_dir:      '%kernel.root_dir%/../var/cache/tmp/pim/file_storage'
    upload_tmp_dir:       '%kernel.root_dir%/../var/cache/tmp/pim/upload_tmp_dir'
