
monolog:
    handlers:
        deprecation:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.deprecations.log'
        deprecation_filter:
            type: filter
            handler: deprecation
            max_level: warning
            channels: ['php']
