akeneo_pim_structure:
    reference_data:
        fabrics:
            class: Acme\Bundle\AppBundle\Entity\Fabric
            type: multi
        color:
            class: Acme\Bundle\AppBundle\Entity\Color
            type: simple

parameters:
    pim_ce_dev_src_folder_location: '%kernel.project_dir%'
    index_hosts: '%env(APP_INDEX_HOSTS)%'
    product_and_product_model_index_name: '%env(APP_PRODUCT_AND_PRODUCT_MODEL_INDEX_NAME)%'
