services:
    pim_user.context.user:
        class: 'Akeneo\UserManagement\Bundle\Context\UserContext'
        public: true
        arguments:
            - '@security.token_storage'
            - '@pim_catalog.repository.locale'
            - '@pim_catalog.repository.channel'
            - '@pim_catalog.repository.category'
            - '@request_stack'
            - '%env(APP_DEFAULT_LOCALE)%'
